parameters: open export files O_TRUNC to discard previous data
 - rcS parameter backup try to directly restore param (FRAM) from backup (in case SD card is removed before successful export)
 - rcS parameter backup logging rearrange to capture more logging output (param_import_fail.txt)
 - posix rcS try to keep param backup and restore roughly in sync with NuttX rcS
 - tinybson fix debug printf format
 - param_export_internal ensure file descriptor positioned at 0 (precaution)

diff --git a/ROMFS/px4fmu_common/init.d-posix/rcS b/ROMFS/px4fmu_common/init.d-posix/rcS
--- a/ROMFS/px4fmu_common/init.d-posix/rcS
+++ b/ROMFS/px4fmu_common/init.d-posix/rcS
@@ -56,19 +56,37 @@ fi
 
 # Load parameters
 set PARAM_FILE eeprom/parameters_"$REQUESTED_AUTOSTART"
-param select $PARAM_FILE
+set PARAM_BACKUP_FILE eeprom/parameters_"$REQUESTED_AUTOSTART"_backup.json
 
-if [ -f $PARAM_FILE ]
+param select $PARAM_FILE
+if ! param import
 then
-	if param load
+	echo "ERROR [init] param import failed"
+
+	param dump $PARAM_FILE
+
+	# try to make a backup copy
+	cp $PARAM_FILE param_import_fail.bson
+
+	# try importing from backup file
+	if [ -f $PARAM_BACKUP_FILE ]
 	then
-		echo "[param] Loaded: $PARAM_FILE"
-	else
-		echo "[param] FAILED loading $PARAM_FILE"
+		echo "[init] importing from parameter backup"
+
+		# dump current backup file contents for comparison
+		param dump $PARAM_BACKUP_FILE
+
+		param import $PARAM_BACKUP_FILE
+
+		# overwrite invalid $PARAM_FILE with backup
+		cp $PARAM_BACKUP_FILE $PARAM_FILE
 	fi
-else
-	echo "[param] parameter file not found, creating $PARAM_FILE"
+
+	param status
 fi
+
+param select-backup $PARAM_BACKUP_FILE
+
 
 # exit early when the minimal shell is requested
 [ $RUN_MINIMAL_SHELL = yes ] && exit 0
